>__1.	Write a Python Program to Add Two Matrices?__

In [8]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)


[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


>__2.	Write a Python Program to Multiply Two Matrices?__

In [9]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j]*Y[i][j]

for r in result:
    print(r)

[9, 16, 21]
[24, 25, 24]
[21, 16, 9]


>__3.	Write a Python Program to Transpose a Matrix?__

In [13]:
import numpy as np
X = [[1,2,3],
    [4 ,5,6]]

matrix = np.array(X)
print(matrix)
print("\n")
print(matrix.T)


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


>__4.	Write a Python Program to Sort Words in Alphabetic Order?__

In [15]:
my_str = "Hello, this Is an Example With cased letters"

words = [word.lower() for word in my_str.split()]

words.sort()

print("The sorted words are:")
for word in words:
   print(word)

The sorted words are:
an
cased
example
hello,
is
letters
this
with


>__5.	Write a Python Program to Remove Punctuation From a String?__

In [16]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

print(no_punct)

Hello he said and went
